### ISSUE TITLE
The project needs a service worker

### ISSUE THREAD

**Issue by louisebolden** [no-mayo/today-i-learned#11]
**Todo:**

- [ ] discuss and plan this feature in more detail
- [ ] extend this checklist with next steps
- [ ] ...
- [ ] check project's PWA status using Google's [Lighthouse](https://developers.google.com/web/tools/lighthouse/) tool
